run:
  skip-dirs:
    - "bin"

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    ignore-generated-header: true
    severity: "warning"
    rules:
      - name: blank-imports
      - name: dot-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  disable-all: false
  enable:
    # code complexity
    - gocyclo
    - gocognit

    # resource leaks
    - bodyclose

    # performance
    - prealloc

    # misc
    - gocritic
    - govet
    - revive
    - misspell
    - exportloopref # exporting pointers for loop variables(bug)
